<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="SHASHANK-HP360" failures="1" tests="1" name="Test" time="12.451" errors="0" timestamp="2021-05-20T21:26:01 IST">
  <testcase classname="com.qa.tests.LoginTests" name="invalidUsernameTest" time="3.791">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.toberemoved]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.toberemoved]
at com.qa.tests.LoginTests.invalidUsernameTest(LoginTests.java:55)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- invalidUsernameTest -->
  <testcase classname="com.qa.tests.LoginTests" name="invalidPasswordTest" time="0.0">
    <ignored/>
  </testcase> <!-- invalidPasswordTest -->
  <testcase classname="com.qa.tests.LoginTests" name="validLoginTest" time="0.0">
    <ignored/>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- Test -->
